server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认的true
    register-with-eureka: true
    #是否从Eureka抓取已有的注册信息，默认为ture，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#            defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本
  instance:
    #更改服务名称
    instance-id: payment8001
    #左下角显示ip地址
    prefer-ip-address: true