server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
       - id: payment_routh             #路由的ID，没有固定规则但是要求唯一，建议配合服务名
#         uri: http://localhost:8001    #匹配后提供服务的路由地址
         uri: lb://cloud-payment-service #匹配后提供服务的路由地址 动态路由配置的前面必须要是lb:
         predicates:
#          Path=/payment/get/**        #断言，路径相匹配的进行路由
          Path=/payment/**
         filters:
           - AddRequestParameter=X-Request-Id,1024  #过滤器工厂会在匹配的请求头上加一对请求头，名为X-Request-Id值为1024
#       - id: payment_routh2             #路由的ID，没有固定规则但是要求唯一，建议配合服务名
#         uri: http://localhost:8001    #匹配后提供服务的路由地址
#         predicates:
#          Path=/payment/get/**        #断言，路径相匹配的进行路由

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
                  defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本